[PR] weekly 렌더 기능 개발
calenderProjectJS/Calendar pull request #26
Opened 2024-04-08 09:06 UTC by dazzlingtea

달력에서 선택한 날짜를 기준으로  weekly 구현하는 함수 

 - calendar의 date-container에서 필요한 날짜들을 weekly의 date-container로 가져가는 개념
 - calendar는 6주 * 7요일이므로 data-date-idx는 언제나 0~41
 - 선택한 날짜의 idx와 요일을 사용해 구현해야하는 한 주를 구할 수 있음
 - 일주일 태그들을 tagDatesWeek 배열에 저장
 
추가 및 수정이 필요한 부분
 - 배열을 weekly의 date-container의 자식으로 추가
 - 초기에 달력에서 클릭하지 않았을 때 weekly에 표시될 주 (오늘 기준)

2024-04-08 14:22 UTC, hoseong511 requested changes
한 번 확인 부탁드려요!

2024-04-08 14:22 UTC, hoseong511 commented on js/calendar.js
> +
둘 째주 부터 출력되려면 이렇게 되어야 할 것 같아요
```suggestion
  for (let i = startDateIdx; i < 7 + startDateIdx; i++) {
    // 3-1. weekly의 시작날짜 태그부터 마지막(토요일) 태그를 배열에 추가
    tagDatesWeek.push($selectedCalendar.children[i].outerHTML);
  }

```

2024-04-08 14:22 UTC, hoseong511 commented on js/calendar.js
> +
```suggestion
  return tagDatesWeek;
```

2024-04-08 14:22 UTC, hoseong511 commented on js/calendar.js
> +export { goToMonth };
```suggestion
export { goToMonth, renderWeeklyView };
```

2024-04-08 14:29 UTC, hoseong511 commented on js/calendar.js
> +  const selectedDateIdx = $selectedDateBox.firstElementChild.dataset.dateIdx;
e.target 이 span이 되면 유효하지 않은 접근이 됩니다. parentElement로 접근하지 않고 closest로 부모 태그를 직접 찾아줘야 할 것 같아요

2024-04-08 23:50 UTC, dazzlingtea commented on js/calendar.js
> +
아 맞아요 수정하겠습니다!

2024-04-08 23:54 UTC, dazzlingtea commented on js/calendar.js
> +
아하 저는 배열 리턴 안하고 바로 weekly date-container 아래에 추가하는 기능을 생각했는데
배열을 받아야할 이유가 있나요?

그럼 e.target 위의 date-container 를 호출한 쪽에서 다시 찾아야 하지 않나요?

2024-04-09 00:26 UTC, hoseong511 commented on js/calendar.js
> +
아하 그렇게 하시려고 했군요! 그래서 renderWeeklyView 로 함수명을 지으신거군요!
저는 나래님이 만들어 주신 함수를 외부에서 사용하려면 반환값이 필요하겠다 싶어서 그랬습니다.
그러면 함수 내부에서 render 로직까지 구현하실 예정이신가요?

2024-04-09 01:06 UTC, dazzlingtea commented on js/calendar.js
> +
주석처리한 부분이 배열로 만든 태그들을 render 해주는 기능입니다 
로그 찍을 때  calendar.html 에서는 weekly가 없어서 에러나기 때문에 주석처리 해둔 거에요

이따가 index.html 로 한 번 테스트 해보려고요

2024-04-09 01:37 UTC, hoseong511 approved these changes

2024-04-09 01:37 UTC, hoseong511 commented
고생하셨습니다!

2024-04-09 01:38 UTC, merged